version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
    timezone: EST
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: "@babel/parser"
    versions:
    - 7.12.15
    - 7.12.17
    - 7.13.13
    - 7.13.15
    - 7.13.16
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
    timezone: EST
  open-pull-requests-limit: 10
