language: node_js
node_js:
  - "12"

branches:
  only:
    - master
    - next
    # npm version tags
    - /^v\d+\.\d+\.\d+/

cache:
  yarn: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install --ignore-engines --frozen-lockfile --non-interactive

script:
  - yarn test

jobs:
  fail_fast: true

  include:
    - stage: tests
      name: "Node 12"
      script:
        - yarn lint:js
        - yarn test

    - stage: additional tests
      name: floating dependencies
      install: yarn install --no-lockfile --ignore-engines

    - name: "Node 6"
      node_js: "8"

    - name: "Node 8"
      node_js: "10"

    - name: "Node 12"
      node_js: "12"

    - name: "Node 13"
      node_js: "13"
